services:
    kebab:
        build:
            context: .
        ports:
            - 80:80
        volumes:
            - .:/var/www
        networks:
            - kebab-network
    mysql_kebab:
        image: 'mysql:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'kebab-mysql:/var/lib/mysql'
        networks:
            - kebab-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    kebab-network:
        driver: bridge
volumes:
    kebab-mysql:
        driver: local
